/* eslint-disable @next/next/no-html-link-for-pages, @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
"use client";
import { useEffect,useMemo,useState } from "react";
const money=(v:number)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default function Cart(){
 const[items,setItems]=useState<any[]>([]);const[settings,setSettings]=useState<any>({});const[form,setForm]=useState<any>({name:"",email:"",phone:"",cep:"",street:"",number:"",neighborhood:"",city:"",state:""});
 useEffect(()=>{setItems(JSON.parse(localStorage.getItem("exale-cart-premium-v1")||"[]"));fetch(`/api/store?t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()).then(d=>setSettings(d.settings||{}))},[]);
 useEffect(()=>localStorage.setItem("exale-cart-premium-v1",JSON.stringify(items)),[items]);
 const total=useMemo(()=>items.reduce((s,i)=>s+(i.promotionalPrice>0?i.promotionalPrice:i.price)*i.quantity,0),[items]);
 async function cep(v:string){setForm((f:any)=>({...f,cep:v}));const d=v.replace(/\D/g,"");if(d.length!==8)return;const r=await fetch(`https://viacep.com.br/ws/${d}/json/`);const x=await r.json();if(!x.erro)setForm((f:any)=>({...f,street:x.logradouro||"",neighborhood:x.bairro||"",city:x.localidade||"",state:x.uf||""}))}
 function finish(){if(!items.length)return alert("Carrinho vazio.");if(!form.name||!form.phone||!form.cep||!form.street||!form.number)return alert("Preencha os campos obrigatórios.");const p=items.map((i,n)=>`${n+1}. ${i.name}\nQuantidade: ${i.quantity}\nSubtotal: ${money((i.promotionalPrice>0?i.promotionalPrice:i.price)*i.quantity)}`).join("\n\n");const m=`*NOVO PEDIDO EXALE*\n\n${p}\n\n*TOTAL: ${money(total)}*\n\nNome: ${form.name}\nE-mail: ${form.email}\nTelefone: ${form.phone}\nEndereço: ${form.street}, ${form.number} - ${form.neighborhood} - ${form.city}/${form.state} - CEP ${form.cep}`;window.location.href=`https://wa.me/${String(settings.whatsapp||"").replace(/\D/g,"")}?text=${encodeURIComponent(m)}`}
 return <main className="cart"><header><a href="/">← Voltar</a><h1>Finalizar compra</h1></header><div className="layout"><section><h2>Seu pedido</h2>{items.length===0&&<p>Carrinho vazio.</p>}{items.map((i,n)=><article key={i.id}><img src={i.imageUrl||"/exale-produto-sem-foto.svg"} alt={i.name}/><div><strong>{i.name}</strong><span>{money(i.promotionalPrice>0?i.promotionalPrice:i.price)}</span><div className="qty"><button onClick={()=>setItems(items.map((x,k)=>k===n?{...x,quantity:Math.max(1,x.quantity-1)}:x))}>−</button><b>{i.quantity}</b><button onClick={()=>setItems(items.map((x,k)=>k===n?{...x,quantity:x.quantity+1}:x))}>+</button></div></div><button className="remove" onClick={()=>setItems(items.filter((_,k)=>k!==n))}>Remover</button></article>)}<div className="total">Total <strong>{money(total)}</strong></div></section><section><h2>Dados para entrega</h2><div className="form">{[["name","Nome completo *"],["email","E-mail"],["phone","Telefone *"],["cep","CEP *"],["street","Rua *"],["number","Número *"],["neighborhood","Bairro"],["city","Cidade"],["state","Estado"]].map(([k,l])=><label key={k}><span>{l}</span><input value={form[k]} onChange={e=>k==="cep"?cep(e.target.value):setForm((f:any)=>({...f,[k]:e.target.value}))}/></label>)}</div><button className="finish" onClick={finish}>Finalizar pelo WhatsApp</button></section></div><style jsx global>{`*{box-sizing:border-box}body{margin:0;background:#f8f1e5;color:#2a160d;font-family:Arial}.cart{min-height:100vh;padding:20px}.cart>header,.layout{width:min(1100px,100%);margin:auto}.cart h1{font-size:48px}.layout{display:grid;grid-template-columns:1fr 1fr;gap:18px}.layout>section{padding:22px;border-radius:24px;background:#fff}.layout article{display:grid;grid-template-columns:80px 1fr auto;gap:12px;align-items:center;padding:10px 0;border-bottom:1px solid #eadfce}.layout article img{width:80px;height:80px;border-radius:14px;object-fit:cover}.layout article strong,.layout article span{display:block}.qty{display:flex;gap:8px;align-items:center;margin-top:8px}.qty button,.remove{border:0;border-radius:999px;padding:7px 10px}.total{display:flex;justify-content:space-between;margin-top:18px;font-size:22px}.form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.form label span{display:block;margin-bottom:5px;font-size:11px;font-weight:900}.form input{width:100%;padding:12px;border:1px solid #dbcab2;border-radius:12px}.finish{width:100%;margin-top:15px;padding:14px;border:0;border-radius:999px;background:#167849;color:#fff;font-weight:950}@media(max-width:800px){.layout{grid-template-columns:1fr}.form{grid-template-columns:1fr}}`}</style></main>
}
